# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.24
# 

Name:       lcms

# >> macros
# << macros

Summary:    Color Management System
Version:    1.19
Release:    1
Group:      Applications/Productivity
License:    MIT
URL:        http://www.littlecms.com/
Source0:    http://www.littlecms.com/lcms-%{version}.tar.gz
Source100:  lcms.yaml
Patch0:     lcms-CVE-2009-0793.patch
Patch1:     lcms-aarch64.patch
BuildRequires:  pkgconfig(zlib)
BuildRequires:  libjpeg-devel
BuildRequires:  libtiff-devel
BuildRequires:  pkgconfig
BuildRequires:  python-devel
BuildRequires:  swig >= 1.3.12
BuildRequires:  automake
BuildRequires:  autoconf
BuildRequires:  libtool
Provides:   littlecms = %{version}-%{release}

%description
LittleCMS intends to be a small-footprint, speed optimized color management
engine in open source form.


%package libs
Summary:    Library for %{name}
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
Obsoletes:   lcms < 1.17-3

%description libs
The %{name}-libs package contains library for %{name}.

%package -n python-%{name}
Summary:    Python interface to LittleCMS
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   python
Provides:   python-littlecms = %{version}-%{release}

%description -n python-%{name}
Python interface to LittleCMS.

%package devel
Summary:    Development files for LittleCMS
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   %{name}-libs = %{version}-%{release}
Requires:   pkgconfig
Provides:   littlecms-devel = %{version}-%{release}

%description devel
Development files for LittleCMS.


%prep
%setup -q -n %{name}-%{version}

# lcms-CVE-2009-0793.patch
%patch0 -p1

# lcms-aarch64.patch
%patch1 -p1
# >> setup
# << setup

%build
# >> build pre
# Convert not UTF-8 files
pushd doc
mkdir -p __temp
for f in LCMSAPI.TXT TUTORIAL.TXT ;do
cp -p $f __temp/$f
iconv -f ISO-8859-1 -t UTF-8 __temp/$f > $f
touch -r __temp/$f $f
done
rm -rf __temp
popd
# << build pre



# >> build post
libtoolize --copy --force
autoreconf -vfi
%configure --with-python --disable-static
(cd python; ./swig_lcms)
make %{?_smp_mflags}


# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
rm -rf ${RPM_BUILD_ROOT}
make install DESTDIR=${RPM_BUILD_ROOT} INSTALL="install -p"
chmod 0644 AUTHORS COPYING ChangeLog NEWS README.1ST doc/TUTORIAL.TXT doc/LCMSAPI.TXT
find ${RPM_BUILD_ROOT} -type f -name "*.la" -exec rm -f {} ';'


# << install post


%post libs -p /sbin/ldconfig

%postun libs -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%doc README.1ST doc/TUTORIAL.TXT
%{_bindir}/*
%{_mandir}/man1/*
# << files

%files libs
%defattr(-,root,root,-)
# >> files libs
%doc AUTHORS COPYING NEWS
%{_libdir}/*.so.*
# << files libs

%files -n python-%{name}
%defattr(-,root,root,-)
# >> files python-%{name}
%{python_sitearch}/lcms.py*
%{python_sitearch}/_lcms.so
# << files python-%{name}

%files devel
%defattr(-,root,root,-)
# >> files devel
%doc doc/LCMSAPI.TXT
%{_includedir}/*
%{_libdir}/*.so
%{_libdir}/pkgconfig/%{name}.pc
# << files devel
